// <auto-generated />
namespace Stack_Exchange_Voting_Utility.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SetupForTheme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetupForTheme));
        
        string IMigrationMetadata.Id
        {
            get { return "201705261123342_SetupForTheme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
